### ISSUE TITLE
tasks file for k8s_master

### ISSUE THREAD

**Issue by jhawthor** [raktim00/Kubernetes-Multi-Node-AWS-Ansible#1]
TASK [k8_master : Add kubeadm repositories on Master Node] *******************************************************************************************************
fatal: [18.224.252.209]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '18.224.252.209' (ECDSA) to the list of known hosts.\r\nec2-user@18.224.252.209: Permission denied (publickey).", "unreachable": true}

**Comment by raktim00** [comment]
If you see EC2 role task file, then you will notice it's waiting for the SSH to come up in last node. That means we are considering, those instances which launched before the last instance's SSH has already started working. By looking at the error it's obvious that there's something wrong in the connectivity, but as per my knowledge I have already allowed all traffic in AWS Security Group. So, I'm unable to understand on which point the connectivity issues is happening.

**Comment by raktim00** [comment]
Please watch the demonstration video & the blog to compare where you made any kind of mistakes - https://github.com/raktim00/Kubernetes-Multi-Node-AWS-Ansible/blob/main/README.md

**Comment by raktim00** [comment]
It's been one week & now I'm closing the issue.
